const plugin: Fig.Plugin = {
  icon: "%",
  displayName: "Lean Prompt",
  name: "lean_miekg",
  type: "shell",
  description: "Pretty, minimal, one-line, fast ZSH prompt",
  authors: [
    {
      name: "miekg",
      github: "miekg",
      twitter: "miekg",
    },
  ],
  github: "miekg/lean",
  license: ["Apache-2.0"],
  shells: ["zsh"],
  categories: ["Prompt"],
  keywords: ["zsh", "prompt", "minimal"],
  installation: {
    origin: "github",
    sourceFiles: ["prompt_lean_setup"],
  },
  configuration: [
    {
      displayName: "Tmux indicator",
      description:
        "Indicator in prompt when in a tmux session. Colored by Color 3.",
      type: "environmentVariable",
      name: "PROMPT_LEAN_TMUX",
      interface: "text",
      default: "t ",
    },
    {
      displayName: "Dirty Git Repo Indicator",
      description:
        "Indicator when current directory is part of a dirty git repo",
      type: "environmentVariable",
      name: "PROMPT_LEAN_VCS",
      interface: "toggle",
      default: true,
    },
    {
      displayName: "Show Current Working Directory",
      description: "Whether to show current directory in the prompt at all",
      type: "environmentVariable",
      name: "PROMPT_LEAN_PWD",
      interface: "toggle",
      default: true,
    },
    {
      displayName: "Current Directory Abbreviation Method",
      hidden: ({ config }) => Boolean(config.PROMPT_LEAN_PWD),
      description: "Shorten cwd path.",
      type: "environmentVariable",
      name: "PROMPT_LEAN_ABBR_METHOD",
      interface: "select",
      default: "truncate",
      options: ["truncate", "shrink"],
    },
    {
      displayName: "Left Prompt Additional Info",
      description: "Display additional information in the left hand prompt",
      type: "environmentVariable",
      name: "PROMPT_LEAN_LEFT",
      interface: "text",
      default: "",
    },
    {
      displayName: "Right Prompt Additional Info",
      description: "Display additional information in the right hand prompt",
      type: "environmentVariable",
      name: "PROMPT_LEAN_RIGHT",
      interface: "text",
      default: "",
    },
    {
      displayName: "Vi-mode Indicator",
      description: "Display an insert mode indicator in Vi-mode",
      type: "environmentVariable",
      name: "PROMPT_LEAN_VIMODE",
      interface: "toggle",
      default: false,
      compile: (value) => (value ? "1" : null),
    },
    {
      displayName: "Vi-mode Format",
      hidden: ({ config }) => Boolean(config.PROMPT_LEAN_VIMODE),
      description: "Format for Vi-mode indicator",
      type: "environmentVariable",
      name: "PROMPT_LEAN_VIMODE_FORMAT",
      interface: "text",
      default: "%F{red}[NORMAL]%f",
    },
    {
      displayName: "Terminal Title",
      description: "Set terminal window title to current running process.",
      type: "environmentVariable",
      name: "PROMPT_LEAN_NOTITLE",
      interface: "toggle",
      default: false,
    },
    {
      displayName: "Color 1",
      description: "Job info and VCS info color",
      type: "environmentVariable",
      name: "PROMPT_LEAN_COLOR1",
      interface: "text",
      default: "242",
    },
    {
      displayName: "Color 2",
      description: "Current working directory color",
      type: "environmentVariable",
      name: "PROMPT_LEAN_COLOR2",
      interface: "text",
      default: "110",
    },
    {
      displayName: "Color 3",
      description: "Tmux Indicator Color",
      type: "environmentVariable",
      name: "PROMPT_LEAN_COLOR3",
      interface: "text",
      default: "150",
    },
  ],
};

export default plugin;
