const colors = [
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  ...new Array(256).fill(null).map((_, i) => `${i}`),
];

const booleanCompile = (value: boolean) => (value ? "true" : "false");

const plugin: Fig.Plugin = {
  name: "spaceship-prompt",
  displayName: "Spaceship Prompt",
  type: "shell",
  description: "A Zsh prompt for Astronauts",
  icon: "images/spaceship.svg",
  screenshots: ["images/1.png"],
  site: "https://spaceship-prompt.sh/",
  docs: "https://spaceship-prompt.sh/getting-started/",
  github: "spaceship-prompt/spaceship-prompt",
  twitter: "SpaceshipPrompt",
  license: ["MIT"],
  shells: ["zsh"],
  categories: ["Prompt"],
  keywords: [
    "zsh",
    "zsh-users",
    "prompt",
    "oh-my-zsh",
    "zsh-theme",
    "shell",
    "spaceship",
    "shell-prompt",
    "terminal",
    "shell-theme",
  ],
  installation: {
    origin: "github",
    sourceFiles: ["spaceship.zsh"],
  },
  configuration: [
    {
      displayName: "Prompt",
      configuration: [
        {
          name: "New Line",
          description: "Adds a newline character before each prompt line",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_PROMPT_ADD_NEWLINE",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
        },
        {
          name: "Separate Line",
          description: "Make the prompt span across two lines",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_PROMPT_SEPARATE_LINE",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
        },
        {
          name: "First Prefix",
          description: "Shows a prefix of the first section in prompt",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_PROMPT_FIRST_PREFIX_SHOW",
          interface: "toggle",
          default: false,
          compile: booleanCompile,
        },
        {
          name: "Show Prefix",
          description: "Show prefixes before prompt sections or not",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_PROMPT_PREFIXES_SHOW",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
        },
        {
          name: "Show Suffix",
          description: "Show suffixes before prompt sections or not",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_PROMPT_SUFFIXES_SHOW",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
        },
        {
          name: "Default Prefix",
          description: "Default prefix for prompt sections",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_PROMPT_DEFAULT_PREFIX",
          interface: "text",
          default: "via ",
        },
        {
          name: "Default Suffix",
          description: "Default suffix for prompt sections",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_PROMPT_DEFAULT_SUFFIX",
          interface: "text",
          default: "",
        },
      ],
    },
    {
      displayName: "Char",
      configuration: [
        {
          name: "Prompt Character Prefix",
          description: "Prefix before prompt character",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_CHAR_PREFIX",
          interface: "text",
          default: "",
        },
        {
          name: "Prompt Character Suffix",
          description: "Suffix after prompt character",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_CHAR_SUFFIX",
          interface: "text",
          default: "",
        },
        {
          name: "Prompt Character",
          description: "Prompt character to be shown before any command",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_CHAR_SYMBOL",
          interface: "text",
          default: "➜",
        },
        {
          name: "Root Prompt Character",
          description:
            "Prompt character to be shown before any command for the root user",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_CHAR_SYMBOL_ROOT",
          interface: "text",
          default: "$SPACESHIP_CHAR_SYMBOL",
        },
        {
          name: "Secondary Prompt Character",
          description:
            "Secondary prompt character to be shown for incomplete commands",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_CHAR_SYMBOL_SECONDARY",
          interface: "text",
          default: "$SPACESHIP_CHAR_SYMBOL",
        },
        {
          name: "Prompt Character Success Color",
          description:
            "Color of prompt character if last command completes successfully",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_CHAR_COLOR_SUCCESS",
          interface: "select",
          options: colors,
          default: "green",
        },
        {
          name: "Prompt Character Failure Color",
          description:
            "Color of prompt character if last command returns non-zero exit-code",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_CHAR_COLOR_FAILURE",
          interface: "select",
          options: colors,
          default: "red",
        },
        {
          name: "Prompt Character Secondary Color",
          description: "Color of secondary prompt character",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_CHAR_COLOR_SECONDARY",
          interface: "select",
          options: colors,
          default: "yellow",
        },
      ],
    },
    {
      displayName: "Time",
      configuration: [
        {
          name: "Show Time",
          description: "Show time in prompt",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_TIME_SHOW",
          interface: "toggle",
          default: false,
          compile: booleanCompile,
        },
        {
          name: "Time Prefix",
          description: "Prefix before time section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_TIME_PREFIX",
          interface: "text",
          default: "at ",
          hidden: ({ config }) => !config.SPACESHIP_TIME_SHOW,
        },
        {
          name: "Time Suffix",
          description: "Suffix after time section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_TIME_SUFFIX",
          interface: "text",
          default: "$SPACESHIP_PROMPT_DEFAULT_SUFFIX",
          hidden: ({ config }) => !config.SPACESHIP_TIME_SHOW,
        },
        {
          name: "Time Color",
          description: "Color of time section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_TIME_COLOR",
          interface: "select",
          options: colors,
          default: "yellow",
          hidden: ({ config }) => !config.SPACESHIP_TIME_SHOW,
        },
        {
          name: "Time Format",
          description:
            "Custom date formatting [ZSH date format](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Date-and-time)",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_TIME_FORMAT",
          interface: "text",
          default: "false",
          hidden: ({ config }) => !config.SPACESHIP_TIME_SHOW,
        },
        {
          name: "12 Hour Time",
          description: "Format time using 12-hour clock (am/pm)",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_TIME_12_HOUR",
          interface: "toggle",
          default: false,
          compile: booleanCompile,
          hidden: ({ config }) => !config.SPACESHIP_TIME_SHOW,
        },
      ],
    },
    {
      displayName: "Username",
      configuration: [
        {
          name: "Show Username",
          description: "Show username in prompt",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_USER_SHOW",
          interface: "select",
          options: ["true", "false", "always", "needed"],
          default: "true",
        },
        {
          name: "Username Prefix",
          description: "Prefix before user section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_USER_PREFIX",
          interface: "text",
          default: "with ",
          hidden: ({ config }) => config.SPACESHIP_USER_SHOW === "false",
        },
        {
          name: "Username Suffix",
          description: "Suffix after user section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_USER_SUFFIX",
          interface: "text",
          default: "$SPACESHIP_PROMPT_DEFAULT_SUFFIX",
          hidden: ({ config }) => config.SPACESHIP_USER_SHOW === "false",
        },
        {
          name: "Username Color",
          description: "Color of user section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_USER_COLOR",
          interface: "select",
          options: colors,
          default: "yellow",
          hidden: ({ config }) => config.SPACESHIP_USER_SHOW === "false",
        },
        {
          name: "Username Root Color",
          description: "Color of user section when it's root",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_USER_COLOR_ROOT",
          interface: "select",
          options: colors,
          default: "red",
          hidden: ({ config }) => config.SPACESHIP_USER_SHOW === "false",
        },
      ],
    },
    {
      displayName: "Hostname",
      configuration: [
        {
          name: "Show hostname section",
          description: "Show hostname in prompt",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_HOST_SHOW",
          interface: "select",
          options: ["true", "false", "always"],
          default: "true",
        },
        {
          name: "Full Hostname",
          description: "Show full hostname in prompt",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_HOST_SHOW_FULL",
          interface: "toggle",
          default: false,
          compile: booleanCompile,
          hidden: ({ config }) => config.SPACESHIP_HOST_SHOW === "false",
        },
        {
          name: "Hostname Prefix",
          description: "Prefix before the connected SSH machine name",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_HOST_PREFIX",
          interface: "text",
          default: "at ",
          hidden: ({ config }) => config.SPACESHIP_HOST_SHOW === "false",
        },
        {
          name: "Hostname Suffix",
          description: "Suffix after the connected SSH machine name",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_HOST_SUFFIX",
          interface: "text",
          default: "$SPACESHIP_PROMPT_DEFAULT_SUFFIX",
          hidden: ({ config }) => config.SPACESHIP_HOST_SHOW === "false",
        },
        {
          name: "Hostname Color",
          description: "Color of hostname section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_HOST_COLOR",
          interface: "select",
          options: colors,
          default: "blue",
          hidden: ({ config }) => config.SPACESHIP_HOST_SHOW === "false",
        },
        {
          name: "SSH Hostname Color",
          description: "Color of host in SSH connection",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_HOST_COLOR_SSH",
          interface: "select",
          options: colors,
          default: "green",
          hidden: ({ config }) => config.SPACESHIP_HOST_SHOW === "false",
        },
      ],
    },
    {
      displayName: "Directory",
      configuration: [
        {
          name: "Show directory section",
          description: "Show directory in prompt",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_DIR_SHOW",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
        },
        {
          name: "Directory Prefix",
          description: "Prefix before current directory",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_DIR_PREFIX",
          interface: "text",
          default: "in ",
          hidden: ({ config }) => !config.SPACESHIP_DIR_SHOW,
        },
        {
          name: "Directory Suffix",
          description: "Suffix after current directory",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_DIR_SUFFIX",
          interface: "text",
          default: "$SPACESHIP_PROMPT_DEFAULT_SUFFIX",
          hidden: ({ config }) => !config.SPACESHIP_DIR_SHOW,
        },
        {
          name: "Directory Truncate",
          description:
            "Number of folders of cwd to show in prompt, `0` to show all",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_DIR_TRUNC",
          interface: "text",
          default: 3,
          hidden: ({ config }) => !config.SPACESHIP_DIR_SHOW,
        },
        {
          name: "Directory Truncate Prefix",
          description:
            "Prefix before cwd when it's truncated. For example `…/` or `.../`, empty to disable",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_DIR_TRUNC_PREFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) => !config.SPACESHIP_DIR_SHOW,
        },
        {
          name: "Directory Truncate Repo",
          description:
            "While in `git` repo, show only root directory and folders inside it",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_DIR_TRUNC_REPO",
          interface: "toggle",
          default: false,
          compile: booleanCompile,
          hidden: ({ config }) => !config.SPACESHIP_DIR_SHOW,
        },
        {
          name: "Directory Color",
          description: "Color of directory section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_DIR_COLOR",
          interface: "select",
          options: colors,
          default: "cyan",
          hidden: ({ config }) => !config.SPACESHIP_DIR_SHOW,
        },
        // TODO: Add lock symbol, only with powerline
      ],
    },
    {
      displayName: "Git",
      configuration: [
        {
          name: "Show Git section",
          description: "Show Git section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_SHOW",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
        },
        {
          name: "Git Prefix",
          description: "Prefix before Git section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_PREFIX",
          interface: "text",
          default: "on ",
          hidden: ({ config }) => !config.SPACESHIP_GIT_SHOW,
        },
        {
          name: "Git Suffix",
          description: "Suffix after Git section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_SUFFIX",
          interface: "text",
          default: "$SPACESHIP_PROMPT_DEFAULT_SUFFIX",
          hidden: ({ config }) => !config.SPACESHIP_GIT_SHOW,
        },
        {
          name: "Git Branch",
          description: "Show Git branch subsection",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_BRANCH_SHOW",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
          hidden: ({ config }) => !config.SPACESHIP_GIT_SHOW,
        },
        {
          name: "Git Branch Prefix",
          description: "Prefix before Git branch subsection",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_BRANCH_PREFIX",
          interface: "text",
          default: "$SPACESHIP_GIT_SYMBOL",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_BRANCH_SHOW),
        },
        {
          name: "Git Branch Suffix",
          description: "Suffix after Git branch subsection",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_BRANCH_SUFFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_BRANCH_SHOW),
        },
        {
          name: "Git Branch Color",
          description: "Color of Git branch subsection",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_BRANCH_COLOR",
          interface: "select",
          options: colors,
          default: "magenta",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_BRANCH_SHOW),
        },
        {
          name: "Git Status",
          description: "Show Git status subsection",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_SHOW",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
          hidden: ({ config }) => !config.SPACESHIP_GIT_SHOW,
        },
        {
          name: "Git Status Prefix",
          description: "Prefix before Git status subsection",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_PREFIX",
          interface: "text",
          default: " [",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Suffix",
          description: "Suffix after Git status subsection",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_SUFFIX",
          interface: "text",
          default: "]",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Color",
          description: "Color of Git status section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_COLOR",
          interface: "select",
          options: colors,
          default: "red",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Untraced Indicator",
          description: "Indicator for untracked changes",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_UNTRACKED",
          interface: "text",
          default: "?",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Added Indicator",
          description: "Indicator for added changes",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_ADDED",
          interface: "text",
          default: "+",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Modified Indicator",
          description: "Indicator for unstaged files",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_MODIFIED",
          interface: "text",
          default: "!",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Renamed Indicator",
          description: "Indicator for renamed files",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_RENAMED",
          interface: "text",
          default: "»",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Deleted Indicator",
          description: "Indicator for deleted files",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_DELETED",
          interface: "text",
          default: "✘",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Stashed Indicator",
          description: "Indicator for stashed changes",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_STASHED",
          interface: "text",
          default: "$",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Unmerged Indicator",
          description: "Indicator for unmerged changes",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_UNMERGED",
          interface: "text",
          default: "=",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Ahead Indicator",
          description:
            "Indicator for unpushed changes (ahead of remote branch)",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_AHEAD",
          interface: "text",
          default: "⇡",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Behind Indicator",
          description:
            "Indicator for unpulled changes (behind of remote branch)",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_BEHIND",
          interface: "text",
          default: "⇣",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
        {
          name: "Git Status Diverged Indicator",
          description:
            "Indicator for diverged changes (diverged from remote branch)",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_GIT_STATUS_DIVERGED",
          interface: "text",
          default: "⇕",
          hidden: ({ config }) =>
            !(config.SPACESHIP_GIT_SHOW && config.SPACESHIP_GIT_STATUS_SHOW),
        },
      ],
    },
    // TODO: Mercuial
    // TODO: Package
    // TODO: Node.js
    // TODO: Ruby
    // TODO: Elm
    // TODO: Elixir
    // TODO: Xcode
    // TODO: Swift
    // TODO: Go
    // TODO: PHP
    // TODO: Rust
    // TODO: Haskell
    // TODO: Julia
    // TODO: Docker
    // TODO: Docker context
    // TODO: Amazon Web Services
    // TODO: Google Cloud Platform
    // TODO: Virtualenv
    // TODO: Conda virtualenv
    // TODO: Pyenv
    // TODO: .NET
    // TODO: Ember.js
    // TODO: Kubernetes
    // TODO: Gradle
    // TODO: Maven
    // TODO: Terraform workspace
    // TODO: IBM Cloud
    {
      displayName: "Execution Time",
      configuration: [
        {
          name: "Execution Time Show",
          description: "Show execution time",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXEC_TIME_SHOW",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
        },
        {
          name: "Execution Time Prefix",
          description: "Prefix for execution time section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXEC_TIME_PREFIX",
          interface: "text",
          default: "took ",
          hidden: ({ config }) => !config.SPACESHIP_EXEC_TIME_SHOW,
        },
        {
          name: "Execution Time Suffix",
          description: "Suffix for execution time section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXEC_TIME_SUFFIX",
          interface: "text",
          default: "$SPACESHIP_PROMPT_DEFAULT_SUFFIX",
          hidden: ({ config }) => !config.SPACESHIP_EXEC_TIME_SHOW,
        },
        {
          name: "Execution Time Color",
          description: "Color for execution time section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXEC_TIME_COLOR",
          interface: "select",
          options: colors,
          default: "yellow",
          hidden: ({ config }) => !config.SPACESHIP_EXEC_TIME_SHOW,
        },
        {
          name: "Execution Time Minimum",
          description:
            "The minimum number of seconds for showing execution time section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXEC_TIME_ELAPSED",
          interface: "text",
          default: 2,
          hidden: ({ config }) => !config.SPACESHIP_EXEC_TIME_SHOW,
        },
      ],
    },
    {
      displayName: "Battery",
      configuration: [
        {
          name: "Battery Show",
          description: "Show battery section or not",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_BATTERY_SHOW",
          interface: "select",
          options: ["true", "false", "always", "charged"],
          default: "true",
        },
        {
          name: "Battery Prefix",
          description: "Prefix for battery section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_BATTERY_PREFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) => config.SPACESHIP_BATTERY_SHOW === "false",
        },
        {
          name: "Battery Suffix",
          description: "Suffix for battery section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_BATTERY_SUFFIX",
          interface: "text",
          default: "$SPACESHIP_PROMPT_DEFAULT_SUFFIX",
          hidden: ({ config }) => config.SPACESHIP_BATTERY_SHOW === "false",
        },
        {
          name: "Battery Charging Symbol",
          description: "Character to be shown if battery is charging",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_BATTERY_SYMBOL_CHARGING",
          interface: "text",
          default: "⇡",
          hidden: ({ config }) => config.SPACESHIP_BATTERY_SHOW === "false",
        },
        {
          name: "Battery Discharging Symbol",
          description: "Character to be shown if battery is discharging",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_BATTERY_SYMBOL_DISCHARGING",
          interface: "text",
          default: "⇣",
          hidden: ({ config }) => config.SPACESHIP_BATTERY_SHOW === "false",
        },
        {
          name: "Battery Full Symbol",
          description: "Character to be shown if battery is full",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_BATTERY_SYMBOL_FULL",
          interface: "text",
          default: " ",
          hidden: ({ config }) => config.SPACESHIP_BATTERY_SHOW === "false",
        },
        {
          name: "Battery Threshold",
          description:
            "Battery level below which battery section will be shown",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_BATTERY_THRESHOLD",
          interface: "text",
          default: 10,
          hidden: ({ config }) => config.SPACESHIP_BATTERY_SHOW === "false",
        },
      ],
    },
    // TODO: Vi-mode
    {
      displayName: "Jobs",
      configuration: [
        {
          name: "Jobs Show",
          description: "Show background jobs indicator",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_JOBS_SHOW",
          interface: "toggle",
          default: true,
          compile: booleanCompile,
        },
        {
          name: "Jobs Prefix",
          description: "Prefix before the jobs indicator",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_JOBS_PREFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) => !config.SPACESHIP_JOBS_SHOW,
        },
        {
          name: "Jobs Suffix",
          description: "Suffix after the jobs indicator",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_JOBS_SUFFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) => !config.SPACESHIP_JOBS_SHOW,
        },
        {
          name: "Jobs Symbol",
          description: "Character to be shown when jobs are hiding",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_JOBS_SYMBOL",
          interface: "text",
          default: "✦",
          hidden: ({ config }) => !config.SPACESHIP_JOBS_SHOW,
        },
        {
          name: "Jobs Color",
          description: "Color of background jobs section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_JOBS_COLOR",
          interface: "select",
          options: colors,
          default: "yellow",
          hidden: ({ config }) => !config.SPACESHIP_JOBS_SHOW,
        },
        {
          name: "Jobs Amount Prefix",
          description:
            "Prefix before the number of jobs (between jobs indicator and jobs amount)",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_JOBS_AMOUNT_PREFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) => !config.SPACESHIP_JOBS_SHOW,
        },
        {
          name: "Jobs Amount Suffix",
          description: "Suffix after the number of jobs",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_JOBS_AMOUNT_SUFFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) => !config.SPACESHIP_JOBS_SHOW,
        },
        {
          name: "Jobs Amount Threshold",
          description: "Number of jobs after which job count will be shown",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_JOBS_AMOUNT_THRESHOLD",
          interface: "text",
          default: 1,
          hidden: ({ config }) => !config.SPACESHIP_JOBS_SHOW,
        },
      ],
    },
    {
      displayName: "Exit Code",
      configuration: [
        {
          name: "Exit Code Show",
          description: "Show exit code of last command",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXIT_CODE_SHOW",
          interface: "toggle",
          default: false,
          compile: booleanCompile,
        },
        {
          name: "Exit Code Prefix",
          description: "Prefix for exit code section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXIT_CODE_PREFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) => !config.SPACESHIP_EXIT_CODE_SHOW,
        },
        {
          name: "Exit Code Suffix",
          description: "Suffix for exit code section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXIT_CODE_SUFFIX",
          interface: "text",
          default: "",
          hidden: ({ config }) => !config.SPACESHIP_EXIT_CODE_SHOW,
        },
        {
          name: "Exit Code Symbol",
          description: "Character to be shown before exit code",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXIT_CODE_SYMBOL",
          interface: "text",
          default: "✘",
          hidden: ({ config }) => !config.SPACESHIP_EXIT_CODE_SHOW,
        },
        {
          name: "Exit Code Color",
          description: "Color for exit code section",
          type: "environmentVariable",
          environmentVariable: "SPACESHIP_EXIT_CODE_COLOR",
          interface: "select",
          options: colors,
          default: "red",
          hidden: ({ config }) => !config.SPACESHIP_EXIT_CODE_SHOW,
        },
      ],
    },
  ],
};

export default plugin;
