const plugin: Fig.Plugin = {
  icon: "👾",
  name: "minimal",
  type: "shell",
  description: "A minimal zsh theme",
  authors: [
    {
      name: "subnixr",
      github: "subnixr",
    },
  ],
  github: "subnixr/minimal",
  license: ["GPL-3.0"],
  shells: ["zsh"],
  categories: ["Prompt"],
  installation: {
    origin: "github",
    sourceFiles: ["minimal.zsh"],
  },
  configuration: [
    {
      displayName: "Prompt Components",
      configuration: [
        {
          displayName: "Left Prompt",
          type: "environmentVariable",
          name: "MNML_PROMPT",
          description: "Components on the left prompt",
          interface: "multiselect",
          default: ["mnml_ssh", "mnml_pyenv", "mnml_status", "mnml_keymap"],
          options: [
            { option: "mnlm_status", displayName: "status" },
            { option: "mnlm_keymap", displayName: "keymap" },
            { option: "'mnlm_cwd 2 0'", displayName: "cwd" },
            { option: "mnlm_git", displayName: "git" },
            { option: "mnlm_hg", displayName: "hg" },
            { option: "mnlm_uhp", displayName: "uhp" },
            { option: "mnlm_ssh", displayName: "ssh" },
            { option: "mnlm_pyenv", displayName: "pyenv" },
            { option: "mnlm_err", displayName: "err" },
            { option: "mnlm_jobs", displayName: "jobs" },
            { option: "mnlm_files", displayName: "files" },
          ],
        },
        {
          displayName: "Right Prompt",
          type: "environmentVariable",
          name: "MNML_RPROMP",
          description: "Components on the right prompt",
          interface: "multiselect",
          default: ["'mnml_cwd 2 0'", "mnml_git"],
          options: [
            { option: "mnlm_status", displayName: "status" },
            { option: "mnlm_keymap", displayName: "keymap" },
            { option: "'mnlm_cwd 2 0'", displayName: "cwd" },
            { option: "mnlm_git", displayName: "git" },
            { option: "mnlm_hg", displayName: "hg" },
            { option: "mnlm_uhp", displayName: "uhp" },
            { option: "mnlm_ssh", displayName: "ssh" },
            { option: "mnlm_pyenv", displayName: "pyenv" },
            { option: "mnlm_err", displayName: "err" },
            { option: "mnlm_jobs", displayName: "jobs" },
            { option: "mnlm_files", displayName: "files" },
          ],
        },
        {
          displayName: "Prompt",
          type: "environmentVariable",
          name: "MNML_INFOLN",
          description: "Components shown on info line",
          interface: "multiselect",
          default: ["mnml_err", "mnml_jobs", "mnml_uhp", "mnml_files"],
          options: [
            { option: "mnlm_status", displayName: "status" },
            { option: "mnlm_keymap", displayName: "keymap" },
            { option: "'mnlm_cwd 2 0'", displayName: "cwd" },
            { option: "mnlm_git", displayName: "git" },
            { option: "mnlm_hg", displayName: "hg" },
            { option: "mnlm_uhp", displayName: "uhp" },
            { option: "mnlm_ssh", displayName: "ssh" },
            { option: "mnlm_pyenv", displayName: "pyenv" },
            { option: "mnlm_err", displayName: "err" },
            { option: "mnlm_jobs", displayName: "jobs" },
            { option: "mnlm_files", displayName: "files" },
          ],
        },
      ],
    },
    {
      name: "MNML_OK_COLOR",
      type: "environmentVariable",
      description: "Color for successful things",
      default: "2",
      interface: "text",
    },
    {
      name: "MNML_ERR_COLOR",
      type: "environmentVariable",
      description: "Color for failures",
      default: 1,
      interface: "text",
    },
    {
      name: "MNML_BGJOB_MODE",
      type: "environmentVariable",
      description: "Mode applied when there are background jobs",
      default: 4,
      interface: "text",
    },
    {
      name: "MNML_USER_CHAR",
      type: "environmentVariable",
      description: "Character used for unprivileged users",
      default: "λ",
      interface: "text",
    },
    {
      name: "MNML_INSERT_CHAR",
      type: "environmentVariable",
      description: "Character used for vi insert mode",
      default: "›",
      interface: "text",
    },
    {
      name: "MNML_NORMAL_CHAR",
      type: "environmentVariable",
      description: "Character used for vi normal mode",
      default: "·",
      interface: "text",
    },
    {
      name: "MNML_ELLIPSIS_CHAR",
      type: "environmentVariable",
      description: "Character used when truncating long words",
      default: "..",
      interface: "text",
    },
  ],
};

export default plugin;
